// Copyright 2011 Howard M. Lewis Ship
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.howardlewisship.tapx.core.components;

import org.apache.tapestry5.Asset;
import org.apache.tapestry5.BindingConstants;
import org.apache.tapestry5.ClientElement;
import org.apache.tapestry5.ComponentResources;
import org.apache.tapestry5.MarkupWriter;
import org.apache.tapestry5.annotations.Environmental;
import org.apache.tapestry5.annotations.Parameter;
import org.apache.tapestry5.annotations.SupportsInformalParameters;
import org.apache.tapestry5.dom.Element;
import org.apache.tapestry5.ioc.annotations.Inject;
import org.apache.tapestry5.services.AssetSource;
import org.apache.tapestry5.services.javascript.JavaScriptSupport;

/**
 * Displays an image from the Silk image set that's bundled inside tapx-core. All images are 16x16 PNGs.
 * The name can be any of the following:
 * <ul>
 * <li>accept</li>
 * <li>add</li>
 * <li>anchor</li>
 * <li>application</li>
 * <li>application_add</li>
 * <li>application_cascade</li>
 * <li>application_delete</li>
 * <li>application_double</li>
 * <li>application_edit</li>
 * <li>application_error</li>
 * <li>application_form</li>
 * <li>application_form_add</li>
 * <li>application_form_delete</li>
 * <li>application_form_edit</li>
 * <li>application_form_magnify</li>
 * <li>application_get</li>
 * <li>application_go</li>
 * <li>application_home</li>
 * <li>application_key</li>
 * <li>application_lightning</li>
 * <li>application_link</li>
 * <li>application_osx</li>
 * <li>application_osx_terminal</li>
 * <li>application_put</li>
 * <li>application_side_boxes</li>
 * <li>application_side_contract</li>
 * <li>application_side_expand</li>
 * <li>application_side_list</li>
 * <li>application_side_tree</li>
 * <li>application_split</li>
 * <li>application_tile_horizontal</li>
 * <li>application_tile_vertical</li>
 * <li>application_view_columns</li>
 * <li>application_view_detail</li>
 * <li>application_view_gallery</li>
 * <li>application_view_icons</li>
 * <li>application_view_list</li>
 * <li>application_view_tile</li>
 * <li>application_xp</li>
 * <li>application_xp_terminal</li>
 * <li>arrow_branch</li>
 * <li>arrow_divide</li>
 * <li>arrow_down</li>
 * <li>arrow_in</li>
 * <li>arrow_inout</li>
 * <li>arrow_join</li>
 * <li>arrow_left</li>
 * <li>arrow_merge</li>
 * <li>arrow_out</li>
 * <li>arrow_redo</li>
 * <li>arrow_refresh</li>
 * <li>arrow_refresh_small</li>
 * <li>arrow_right</li>
 * <li>arrow_rotate_anticlockwise</li>
 * <li>arrow_rotate_clockwise</li>
 * <li>arrow_switch</li>
 * <li>arrow_turn_left</li>
 * <li>arrow_turn_right</li>
 * <li>arrow_undo</li>
 * <li>arrow_up</li>
 * <li>asterisk_orange</li>
 * <li>asterisk_yellow</li>
 * <li>attach</li>
 * <li>award_star_add</li>
 * <li>award_star_bronze_1</li>
 * <li>award_star_bronze_2</li>
 * <li>award_star_bronze_3</li>
 * <li>award_star_delete</li>
 * <li>award_star_gold_1</li>
 * <li>award_star_gold_2</li>
 * <li>award_star_gold_3</li>
 * <li>award_star_silver_1</li>
 * <li>award_star_silver_2</li>
 * <li>award_star_silver_3</li>
 * <li>basket</li>
 * <li>basket_add</li>
 * <li>basket_delete</li>
 * <li>basket_edit</li>
 * <li>basket_error</li>
 * <li>basket_go</li>
 * <li>basket_put</li>
 * <li>basket_remove</li>
 * <li>bell</li>
 * <li>bell_add</li>
 * <li>bell_delete</li>
 * <li>bell_error</li>
 * <li>bell_go</li>
 * <li>bell_link</li>
 * <li>bin</li>
 * <li>bin_closed</li>
 * <li>bin_empty</li>
 * <li>bomb</li>
 * <li>book</li>
 * <li>book_add</li>
 * <li>book_addresses</li>
 * <li>book_delete</li>
 * <li>book_edit</li>
 * <li>book_error</li>
 * <li>book_go</li>
 * <li>book_key</li>
 * <li>book_link</li>
 * <li>book_next</li>
 * <li>book_open</li>
 * <li>book_previous</li>
 * <li>box</li>
 * <li>brick</li>
 * <li>brick_add</li>
 * <li>brick_delete</li>
 * <li>brick_edit</li>
 * <li>brick_error</li>
 * <li>brick_go</li>
 * <li>brick_link</li>
 * <li>bricks</li>
 * <li>briefcase</li>
 * <li>bug</li>
 * <li>bug_add</li>
 * <li>bug_delete</li>
 * <li>bug_edit</li>
 * <li>bug_error</li>
 * <li>bug_go</li>
 * <li>bug_link</li>
 * <li>building</li>
 * <li>building_add</li>
 * <li>building_delete</li>
 * <li>building_edit</li>
 * <li>building_error</li>
 * <li>building_go</li>
 * <li>building_key</li>
 * <li>building_link</li>
 * <li>bullet_add</li>
 * <li>bullet_arrow_bottom</li>
 * <li>bullet_arrow_down</li>
 * <li>bullet_arrow_top</li>
 * <li>bullet_arrow_up</li>
 * <li>bullet_black</li>
 * <li>bullet_blue</li>
 * <li>bullet_delete</li>
 * <li>bullet_disk</li>
 * <li>bullet_error</li>
 * <li>bullet_feed</li>
 * <li>bullet_go</li>
 * <li>bullet_green</li>
 * <li>bullet_key</li>
 * <li>bullet_orange</li>
 * <li>bullet_picture</li>
 * <li>bullet_pink</li>
 * <li>bullet_purple</li>
 * <li>bullet_red</li>
 * <li>bullet_star</li>
 * <li>bullet_toggle_minus</li>
 * <li>bullet_toggle_plus</li>
 * <li>bullet_white</li>
 * <li>bullet_wrench</li>
 * <li>bullet_yellow</li>
 * <li>cake</li>
 * <li>calculator</li>
 * <li>calculator_add</li>
 * <li>calculator_delete</li>
 * <li>calculator_edit</li>
 * <li>calculator_error</li>
 * <li>calculator_link</li>
 * <li>calendar</li>
 * <li>calendar_add</li>
 * <li>calendar_delete</li>
 * <li>calendar_edit</li>
 * <li>calendar_link</li>
 * <li>calendar_view_day</li>
 * <li>calendar_view_month</li>
 * <li>calendar_view_week</li>
 * <li>camera</li>
 * <li>camera_add</li>
 * <li>camera_delete</li>
 * <li>camera_edit</li>
 * <li>camera_error</li>
 * <li>camera_go</li>
 * <li>camera_link</li>
 * <li>camera_small</li>
 * <li>cancel</li>
 * <li>car</li>
 * <li>car_add</li>
 * <li>car_delete</li>
 * <li>cart</li>
 * <li>cart_add</li>
 * <li>cart_delete</li>
 * <li>cart_edit</li>
 * <li>cart_error</li>
 * <li>cart_go</li>
 * <li>cart_put</li>
 * <li>cart_remove</li>
 * <li>cd</li>
 * <li>cd_add</li>
 * <li>cd_burn</li>
 * <li>cd_delete</li>
 * <li>cd_edit</li>
 * <li>cd_eject</li>
 * <li>cd_go</li>
 * <li>chart_bar</li>
 * <li>chart_bar_add</li>
 * <li>chart_bar_delete</li>
 * <li>chart_bar_edit</li>
 * <li>chart_bar_error</li>
 * <li>chart_bar_link</li>
 * <li>chart_curve</li>
 * <li>chart_curve_add</li>
 * <li>chart_curve_delete</li>
 * <li>chart_curve_edit</li>
 * <li>chart_curve_error</li>
 * <li>chart_curve_go</li>
 * <li>chart_curve_link</li>
 * <li>chart_line</li>
 * <li>chart_line_add</li>
 * <li>chart_line_delete</li>
 * <li>chart_line_edit</li>
 * <li>chart_line_error</li>
 * <li>chart_line_link</li>
 * <li>chart_organisation</li>
 * <li>chart_organisation_add</li>
 * <li>chart_organisation_delete</li>
 * <li>chart_pie</li>
 * <li>chart_pie_add</li>
 * <li>chart_pie_delete</li>
 * <li>chart_pie_edit</li>
 * <li>chart_pie_error</li>
 * <li>chart_pie_link</li>
 * <li>clock</li>
 * <li>clock_add</li>
 * <li>clock_delete</li>
 * <li>clock_edit</li>
 * <li>clock_error</li>
 * <li>clock_go</li>
 * <li>clock_link</li>
 * <li>clock_pause</li>
 * <li>clock_play</li>
 * <li>clock_red</li>
 * <li>clock_stop</li>
 * <li>cog</li>
 * <li>cog_add</li>
 * <li>cog_delete</li>
 * <li>cog_edit</li>
 * <li>cog_error</li>
 * <li>cog_go</li>
 * <li>coins</li>
 * <li>coins_add</li>
 * <li>coins_delete</li>
 * <li>color_swatch</li>
 * <li>color_wheel</li>
 * <li>comment</li>
 * <li>comment_add</li>
 * <li>comment_delete</li>
 * <li>comment_edit</li>
 * <li>comments</li>
 * <li>comments_add</li>
 * <li>comments_delete</li>
 * <li>compress</li>
 * <li>computer</li>
 * <li>computer_add</li>
 * <li>computer_delete</li>
 * <li>computer_edit</li>
 * <li>computer_error</li>
 * <li>computer_go</li>
 * <li>computer_key</li>
 * <li>computer_link</li>
 * <li>connect</li>
 * <li>contrast</li>
 * <li>contrast_decrease</li>
 * <li>contrast_high</li>
 * <li>contrast_increase</li>
 * <li>contrast_low</li>
 * <li>control_eject</li>
 * <li>control_eject_blue</li>
 * <li>control_end</li>
 * <li>control_end_blue</li>
 * <li>control_equalizer</li>
 * <li>control_equalizer_blue</li>
 * <li>control_fastforward</li>
 * <li>control_fastforward_blue</li>
 * <li>control_pause</li>
 * <li>control_pause_blue</li>
 * <li>control_play</li>
 * <li>control_play_blue</li>
 * <li>control_repeat</li>
 * <li>control_repeat_blue</li>
 * <li>control_rewind</li>
 * <li>control_rewind_blue</li>
 * <li>control_start</li>
 * <li>control_start_blue</li>
 * <li>control_stop</li>
 * <li>control_stop_blue</li>
 * <li>controller</li>
 * <li>controller_add</li>
 * <li>controller_delete</li>
 * <li>controller_error</li>
 * <li>creditcards</li>
 * <li>cross</li>
 * <li>css</li>
 * <li>css_add</li>
 * <li>css_delete</li>
 * <li>css_go</li>
 * <li>css_valid</li>
 * <li>cup</li>
 * <li>cup_add</li>
 * <li>cup_delete</li>
 * <li>cup_edit</li>
 * <li>cup_error</li>
 * <li>cup_go</li>
 * <li>cup_key</li>
 * <li>cup_link</li>
 * <li>cursor</li>
 * <li>cut</li>
 * <li>cut_red</li>
 * <li>database</li>
 * <li>database_add</li>
 * <li>database_connect</li>
 * <li>database_delete</li>
 * <li>database_edit</li>
 * <li>database_error</li>
 * <li>database_gear</li>
 * <li>database_go</li>
 * <li>database_key</li>
 * <li>database_lightning</li>
 * <li>database_link</li>
 * <li>database_refresh</li>
 * <li>database_save</li>
 * <li>database_table</li>
 * <li>date</li>
 * <li>date_add</li>
 * <li>date_delete</li>
 * <li>date_edit</li>
 * <li>date_error</li>
 * <li>date_go</li>
 * <li>date_link</li>
 * <li>date_magnify</li>
 * <li>date_next</li>
 * <li>date_previous</li>
 * <li>delete</li>
 * <li>disconnect</li>
 * <li>disk</li>
 * <li>disk_multiple</li>
 * <li>door</li>
 * <li>door_in</li>
 * <li>door_open</li>
 * <li>door_out</li>
 * <li>drink</li>
 * <li>drink_empty</li>
 * <li>drive</li>
 * <li>drive_add</li>
 * <li>drive_burn</li>
 * <li>drive_cd</li>
 * <li>drive_cd_empty</li>
 * <li>drive_delete</li>
 * <li>drive_disk</li>
 * <li>drive_edit</li>
 * <li>drive_error</li>
 * <li>drive_go</li>
 * <li>drive_key</li>
 * <li>drive_link</li>
 * <li>drive_magnify</li>
 * <li>drive_network</li>
 * <li>drive_rename</li>
 * <li>drive_user</li>
 * <li>drive_web</li>
 * <li>dvd</li>
 * <li>dvd_add</li>
 * <li>dvd_delete</li>
 * <li>dvd_edit</li>
 * <li>dvd_error</li>
 * <li>dvd_go</li>
 * <li>dvd_key</li>
 * <li>dvd_link</li>
 * <li>email</li>
 * <li>email_add</li>
 * <li>email_attach</li>
 * <li>email_delete</li>
 * <li>email_edit</li>
 * <li>email_error</li>
 * <li>email_go</li>
 * <li>email_link</li>
 * <li>email_open</li>
 * <li>email_open_image</li>
 * <li>emoticon_evilgrin</li>
 * <li>emoticon_grin</li>
 * <li>emoticon_happy</li>
 * <li>emoticon_smile</li>
 * <li>emoticon_surprised</li>
 * <li>emoticon_tongue</li>
 * <li>emoticon_unhappy</li>
 * <li>emoticon_waii</li>
 * <li>emoticon_wink</li>
 * <li>error</li>
 * <li>error_add</li>
 * <li>error_delete</li>
 * <li>error_go</li>
 * <li>exclamation</li>
 * <li>eye</li>
 * <li>feed</li>
 * <li>feed_add</li>
 * <li>feed_delete</li>
 * <li>feed_disk</li>
 * <li>feed_edit</li>
 * <li>feed_error</li>
 * <li>feed_go</li>
 * <li>feed_key</li>
 * <li>feed_link</li>
 * <li>feed_magnify</li>
 * <li>female</li>
 * <li>film</li>
 * <li>film_add</li>
 * <li>film_delete</li>
 * <li>film_edit</li>
 * <li>film_error</li>
 * <li>film_go</li>
 * <li>film_key</li>
 * <li>film_link</li>
 * <li>film_save</li>
 * <li>find</li>
 * <li>flag_blue</li>
 * <li>flag_green</li>
 * <li>flag_orange</li>
 * <li>flag_pink</li>
 * <li>flag_purple</li>
 * <li>flag_red</li>
 * <li>flag_yellow</li>
 * <li>folder</li>
 * <li>folder_add</li>
 * <li>folder_bell</li>
 * <li>folder_brick</li>
 * <li>folder_bug</li>
 * <li>folder_camera</li>
 * <li>folder_database</li>
 * <li>folder_delete</li>
 * <li>folder_edit</li>
 * <li>folder_error</li>
 * <li>folder_explore</li>
 * <li>folder_feed</li>
 * <li>folder_find</li>
 * <li>folder_go</li>
 * <li>folder_heart</li>
 * <li>folder_image</li>
 * <li>folder_key</li>
 * <li>folder_lightbulb</li>
 * <li>folder_link</li>
 * <li>folder_magnify</li>
 * <li>folder_page</li>
 * <li>folder_page_white</li>
 * <li>folder_palette</li>
 * <li>folder_picture</li>
 * <li>folder_star</li>
 * <li>folder_table</li>
 * <li>folder_user</li>
 * <li>folder_wrench</li>
 * <li>font</li>
 * <li>font_add</li>
 * <li>font_delete</li>
 * <li>font_go</li>
 * <li>group</li>
 * <li>group_add</li>
 * <li>group_delete</li>
 * <li>group_edit</li>
 * <li>group_error</li>
 * <li>group_gear</li>
 * <li>group_go</li>
 * <li>group_key</li>
 * <li>group_link</li>
 * <li>heart</li>
 * <li>heart_add</li>
 * <li>heart_delete</li>
 * <li>help</li>
 * <li>hourglass</li>
 * <li>hourglass_add</li>
 * <li>hourglass_delete</li>
 * <li>hourglass_go</li>
 * <li>hourglass_link</li>
 * <li>house</li>
 * <li>house_go</li>
 * <li>house_link</li>
 * <li>html</li>
 * <li>html_add</li>
 * <li>html_delete</li>
 * <li>html_go</li>
 * <li>html_valid</li>
 * <li>image</li>
 * <li>image_add</li>
 * <li>image_delete</li>
 * <li>image_edit</li>
 * <li>image_link</li>
 * <li>images</li>
 * <li>information</li>
 * <li>ipod</li>
 * <li>ipod_cast</li>
 * <li>ipod_cast_add</li>
 * <li>ipod_cast_delete</li>
 * <li>ipod_sound</li>
 * <li>joystick</li>
 * <li>joystick_add</li>
 * <li>joystick_delete</li>
 * <li>joystick_error</li>
 * <li>key</li>
 * <li>key_add</li>
 * <li>key_delete</li>
 * <li>key_go</li>
 * <li>keyboard</li>
 * <li>keyboard_add</li>
 * <li>keyboard_delete</li>
 * <li>keyboard_magnify</li>
 * <li>layers</li>
 * <li>layout</li>
 * <li>layout_add</li>
 * <li>layout_content</li>
 * <li>layout_delete</li>
 * <li>layout_edit</li>
 * <li>layout_error</li>
 * <li>layout_header</li>
 * <li>layout_link</li>
 * <li>layout_sidebar</li>
 * <li>lightbulb</li>
 * <li>lightbulb_add</li>
 * <li>lightbulb_delete</li>
 * <li>lightbulb_off</li>
 * <li>lightning</li>
 * <li>lightning_add</li>
 * <li>lightning_delete</li>
 * <li>lightning_go</li>
 * <li>link</li>
 * <li>link_add</li>
 * <li>link_break</li>
 * <li>link_delete</li>
 * <li>link_edit</li>
 * <li>link_error</li>
 * <li>link_go</li>
 * <li>lock</li>
 * <li>lock_add</li>
 * <li>lock_break</li>
 * <li>lock_delete</li>
 * <li>lock_edit</li>
 * <li>lock_go</li>
 * <li>lock_open</li>
 * <li>lorry</li>
 * <li>lorry_add</li>
 * <li>lorry_delete</li>
 * <li>lorry_error</li>
 * <li>lorry_flatbed</li>
 * <li>lorry_go</li>
 * <li>lorry_link</li>
 * <li>magifier_zoom_out</li>
 * <li>magnifier</li>
 * <li>magnifier_zoom_in</li>
 * <li>male</li>
 * <li>map</li>
 * <li>map_add</li>
 * <li>map_delete</li>
 * <li>map_edit</li>
 * <li>map_go</li>
 * <li>map_magnify</li>
 * <li>medal_bronze_1</li>
 * <li>medal_bronze_2</li>
 * <li>medal_bronze_3</li>
 * <li>medal_bronze_add</li>
 * <li>medal_bronze_delete</li>
 * <li>medal_gold_1</li>
 * <li>medal_gold_2</li>
 * <li>medal_gold_3</li>
 * <li>medal_gold_add</li>
 * <li>medal_gold_delete</li>
 * <li>medal_silver_1</li>
 * <li>medal_silver_2</li>
 * <li>medal_silver_3</li>
 * <li>medal_silver_add</li>
 * <li>medal_silver_delete</li>
 * <li>money</li>
 * <li>money_add</li>
 * <li>money_delete</li>
 * <li>money_dollar</li>
 * <li>money_euro</li>
 * <li>money_pound</li>
 * <li>money_yen</li>
 * <li>monitor</li>
 * <li>monitor_add</li>
 * <li>monitor_delete</li>
 * <li>monitor_edit</li>
 * <li>monitor_error</li>
 * <li>monitor_go</li>
 * <li>monitor_lightning</li>
 * <li>monitor_link</li>
 * <li>mouse</li>
 * <li>mouse_add</li>
 * <li>mouse_delete</li>
 * <li>mouse_error</li>
 * <li>music</li>
 * <li>new</li>
 * <li>newspaper</li>
 * <li>newspaper_add</li>
 * <li>newspaper_delete</li>
 * <li>newspaper_go</li>
 * <li>newspaper_link</li>
 * <li>note</li>
 * <li>note_add</li>
 * <li>note_delete</li>
 * <li>note_edit</li>
 * <li>note_error</li>
 * <li>note_go</li>
 * <li>overlays</li>
 * <li>package</li>
 * <li>package_add</li>
 * <li>package_delete</li>
 * <li>package_go</li>
 * <li>package_green</li>
 * <li>package_link</li>
 * <li>page</li>
 * <li>page_add</li>
 * <li>page_attach</li>
 * <li>page_code</li>
 * <li>page_copy</li>
 * <li>page_delete</li>
 * <li>page_edit</li>
 * <li>page_error</li>
 * <li>page_excel</li>
 * <li>page_find</li>
 * <li>page_gear</li>
 * <li>page_go</li>
 * <li>page_green</li>
 * <li>page_key</li>
 * <li>page_lightning</li>
 * <li>page_link</li>
 * <li>page_paintbrush</li>
 * <li>page_paste</li>
 * <li>page_red</li>
 * <li>page_refresh</li>
 * <li>page_save</li>
 * <li>page_white</li>
 * <li>page_white_acrobat</li>
 * <li>page_white_actionscript</li>
 * <li>page_white_add</li>
 * <li>page_white_c</li>
 * <li>page_white_camera</li>
 * <li>page_white_cd</li>
 * <li>page_white_code</li>
 * <li>page_white_code_red</li>
 * <li>page_white_coldfusion</li>
 * <li>page_white_compressed</li>
 * <li>page_white_copy</li>
 * <li>page_white_cplusplus</li>
 * <li>page_white_csharp</li>
 * <li>page_white_cup</li>
 * <li>page_white_database</li>
 * <li>page_white_delete</li>
 * <li>page_white_dvd</li>
 * <li>page_white_edit</li>
 * <li>page_white_error</li>
 * <li>page_white_excel</li>
 * <li>page_white_find</li>
 * <li>page_white_flash</li>
 * <li>page_white_freehand</li>
 * <li>page_white_gear</li>
 * <li>page_white_get</li>
 * <li>page_white_go</li>
 * <li>page_white_h</li>
 * <li>page_white_horizontal</li>
 * <li>page_white_key</li>
 * <li>page_white_lightning</li>
 * <li>page_white_link</li>
 * <li>page_white_magnify</li>
 * <li>page_white_medal</li>
 * <li>page_white_office</li>
 * <li>page_white_paint</li>
 * <li>page_white_paintbrush</li>
 * <li>page_white_paste</li>
 * <li>page_white_php</li>
 * <li>page_white_picture</li>
 * <li>page_white_powerpoint</li>
 * <li>page_white_put</li>
 * <li>page_white_ruby</li>
 * <li>page_white_stack</li>
 * <li>page_white_star</li>
 * <li>page_white_swoosh</li>
 * <li>page_white_text</li>
 * <li>page_white_text_width</li>
 * <li>page_white_tux</li>
 * <li>page_white_vector</li>
 * <li>page_white_visualstudio</li>
 * <li>page_white_width</li>
 * <li>page_white_word</li>
 * <li>page_white_world</li>
 * <li>page_white_wrench</li>
 * <li>page_white_zip</li>
 * <li>page_word</li>
 * <li>page_world</li>
 * <li>paintbrush</li>
 * <li>paintcan</li>
 * <li>palette</li>
 * <li>paste_plain</li>
 * <li>paste_word</li>
 * <li>pencil</li>
 * <li>pencil_add</li>
 * <li>pencil_delete</li>
 * <li>pencil_go</li>
 * <li>phone</li>
 * <li>phone_add</li>
 * <li>phone_delete</li>
 * <li>phone_sound</li>
 * <li>photo</li>
 * <li>photo_add</li>
 * <li>photo_delete</li>
 * <li>photo_link</li>
 * <li>photos</li>
 * <li>picture</li>
 * <li>picture_add</li>
 * <li>picture_delete</li>
 * <li>picture_edit</li>
 * <li>picture_empty</li>
 * <li>picture_error</li>
 * <li>picture_go</li>
 * <li>picture_key</li>
 * <li>picture_link</li>
 * <li>picture_save</li>
 * <li>pictures</li>
 * <li>pilcrow</li>
 * <li>pill</li>
 * <li>pill_add</li>
 * <li>pill_delete</li>
 * <li>pill_go</li>
 * <li>plugin</li>
 * <li>plugin_add</li>
 * <li>plugin_delete</li>
 * <li>plugin_disabled</li>
 * <li>plugin_edit</li>
 * <li>plugin_error</li>
 * <li>plugin_go</li>
 * <li>plugin_link</li>
 * <li>printer</li>
 * <li>printer_add</li>
 * <li>printer_delete</li>
 * <li>printer_empty</li>
 * <li>printer_error</li>
 * <li>rainbow</li>
 * <li>report</li>
 * <li>report_add</li>
 * <li>report_delete</li>
 * <li>report_disk</li>
 * <li>report_edit</li>
 * <li>report_go</li>
 * <li>report_key</li>
 * <li>report_link</li>
 * <li>report_magnify</li>
 * <li>report_picture</li>
 * <li>report_user</li>
 * <li>report_word</li>
 * <li>resultset_first</li>
 * <li>resultset_last</li>
 * <li>resultset_next</li>
 * <li>resultset_previous</li>
 * <li>rosette</li>
 * <li>rss</li>
 * <li>rss_add</li>
 * <li>rss_delete</li>
 * <li>rss_go</li>
 * <li>rss_valid</li>
 * <li>ruby</li>
 * <li>ruby_add</li>
 * <li>ruby_delete</li>
 * <li>ruby_gear</li>
 * <li>ruby_get</li>
 * <li>ruby_go</li>
 * <li>ruby_key</li>
 * <li>ruby_link</li>
 * <li>ruby_put</li>
 * <li>script</li>
 * <li>script_add</li>
 * <li>script_code</li>
 * <li>script_code_red</li>
 * <li>script_delete</li>
 * <li>script_edit</li>
 * <li>script_error</li>
 * <li>script_gear</li>
 * <li>script_go</li>
 * <li>script_key</li>
 * <li>script_lightning</li>
 * <li>script_link</li>
 * <li>script_palette</li>
 * <li>script_save</li>
 * <li>server</li>
 * <li>server_add</li>
 * <li>server_chart</li>
 * <li>server_compressed</li>
 * <li>server_connect</li>
 * <li>server_database</li>
 * <li>server_delete</li>
 * <li>server_edit</li>
 * <li>server_error</li>
 * <li>server_go</li>
 * <li>server_key</li>
 * <li>server_lightning</li>
 * <li>server_link</li>
 * <li>server_uncompressed</li>
 * <li>shading</li>
 * <li>shape_align_bottom</li>
 * <li>shape_align_center</li>
 * <li>shape_align_left</li>
 * <li>shape_align_middle</li>
 * <li>shape_align_right</li>
 * <li>shape_align_top</li>
 * <li>shape_flip_horizontal</li>
 * <li>shape_flip_vertical</li>
 * <li>shape_group</li>
 * <li>shape_handles</li>
 * <li>shape_move_back</li>
 * <li>shape_move_backwards</li>
 * <li>shape_move_forwards</li>
 * <li>shape_move_front</li>
 * <li>shape_rotate_anticlockwise</li>
 * <li>shape_rotate_clockwise</li>
 * <li>shape_square</li>
 * <li>shape_square_add</li>
 * <li>shape_square_delete</li>
 * <li>shape_square_edit</li>
 * <li>shape_square_error</li>
 * <li>shape_square_go</li>
 * <li>shape_square_key</li>
 * <li>shape_square_link</li>
 * <li>shape_ungroup</li>
 * <li>shield</li>
 * <li>shield_add</li>
 * <li>shield_delete</li>
 * <li>shield_go</li>
 * <li>sitemap</li>
 * <li>sitemap_color</li>
 * <li>sound</li>
 * <li>sound_add</li>
 * <li>sound_delete</li>
 * <li>sound_low</li>
 * <li>sound_mute</li>
 * <li>sound_none</li>
 * <li>spellcheck</li>
 * <li>sport_8ball</li>
 * <li>sport_basketball</li>
 * <li>sport_football</li>
 * <li>sport_golf</li>
 * <li>sport_raquet</li>
 * <li>sport_shuttlecock</li>
 * <li>sport_soccer</li>
 * <li>sport_tennis</li>
 * <li>star</li>
 * <li>status_away</li>
 * <li>status_busy</li>
 * <li>status_offline</li>
 * <li>status_online</li>
 * <li>stop</li>
 * <li>style</li>
 * <li>style_add</li>
 * <li>style_delete</li>
 * <li>style_edit</li>
 * <li>style_go</li>
 * <li>sum</li>
 * <li>tab</li>
 * <li>tab_add</li>
 * <li>tab_delete</li>
 * <li>tab_edit</li>
 * <li>tab_go</li>
 * <li>table</li>
 * <li>table_add</li>
 * <li>table_delete</li>
 * <li>table_edit</li>
 * <li>table_error</li>
 * <li>table_gear</li>
 * <li>table_go</li>
 * <li>table_key</li>
 * <li>table_lightning</li>
 * <li>table_link</li>
 * <li>table_multiple</li>
 * <li>table_refresh</li>
 * <li>table_relationship</li>
 * <li>table_row_delete</li>
 * <li>table_row_insert</li>
 * <li>table_save</li>
 * <li>table_sort</li>
 * <li>tag</li>
 * <li>tag_blue</li>
 * <li>tag_blue_add</li>
 * <li>tag_blue_delete</li>
 * <li>tag_blue_edit</li>
 * <li>tag_green</li>
 * <li>tag_orange</li>
 * <li>tag_pink</li>
 * <li>tag_purple</li>
 * <li>tag_red</li>
 * <li>tag_yellow</li>
 * <li>telephone</li>
 * <li>telephone_add</li>
 * <li>telephone_delete</li>
 * <li>telephone_edit</li>
 * <li>telephone_error</li>
 * <li>telephone_go</li>
 * <li>telephone_key</li>
 * <li>telephone_link</li>
 * <li>television</li>
 * <li>television_add</li>
 * <li>television_delete</li>
 * <li>text_align_center</li>
 * <li>text_align_justify</li>
 * <li>text_align_left</li>
 * <li>text_align_right</li>
 * <li>text_allcaps</li>
 * <li>text_bold</li>
 * <li>text_columns</li>
 * <li>text_dropcaps</li>
 * <li>text_heading_1</li>
 * <li>text_heading_2</li>
 * <li>text_heading_3</li>
 * <li>text_heading_4</li>
 * <li>text_heading_5</li>
 * <li>text_heading_6</li>
 * <li>text_horizontalrule</li>
 * <li>text_indent</li>
 * <li>text_indent_remove</li>
 * <li>text_italic</li>
 * <li>text_kerning</li>
 * <li>text_letter_omega</li>
 * <li>text_letterspacing</li>
 * <li>text_linespacing</li>
 * <li>text_list_bullets</li>
 * <li>text_list_numbers</li>
 * <li>text_lowercase</li>
 * <li>text_padding_bottom</li>
 * <li>text_padding_left</li>
 * <li>text_padding_right</li>
 * <li>text_padding_top</li>
 * <li>text_replace</li>
 * <li>text_signature</li>
 * <li>text_smallcaps</li>
 * <li>text_strikethrough</li>
 * <li>text_subscript</li>
 * <li>text_superscript</li>
 * <li>text_underline</li>
 * <li>text_uppercase</li>
 * <li>textfield</li>
 * <li>textfield_add</li>
 * <li>textfield_delete</li>
 * <li>textfield_key</li>
 * <li>textfield_rename</li>
 * <li>thumb_down</li>
 * <li>thumb_up</li>
 * <li>tick</li>
 * <li>time</li>
 * <li>time_add</li>
 * <li>time_delete</li>
 * <li>time_go</li>
 * <li>timeline_marker</li>
 * <li>transmit</li>
 * <li>transmit_add</li>
 * <li>transmit_blue</li>
 * <li>transmit_delete</li>
 * <li>transmit_edit</li>
 * <li>transmit_error</li>
 * <li>transmit_go</li>
 * <li>tux</li>
 * <li>user</li>
 * <li>user_add</li>
 * <li>user_comment</li>
 * <li>user_delete</li>
 * <li>user_edit</li>
 * <li>user_female</li>
 * <li>user_go</li>
 * <li>user_gray</li>
 * <li>user_green</li>
 * <li>user_orange</li>
 * <li>user_red</li>
 * <li>user_suit</li>
 * <li>vcard</li>
 * <li>vcard_add</li>
 * <li>vcard_delete</li>
 * <li>vcard_edit</li>
 * <li>vector</li>
 * <li>vector_add</li>
 * <li>vector_delete</li>
 * <li>wand</li>
 * <li>weather_clouds</li>
 * <li>weather_cloudy</li>
 * <li>weather_lightning</li>
 * <li>weather_rain</li>
 * <li>weather_snow</li>
 * <li>weather_sun</li>
 * <li>webcam</li>
 * <li>webcam_add</li>
 * <li>webcam_delete</li>
 * <li>webcam_error</li>
 * <li>world</li>
 * <li>world_add</li>
 * <li>world_delete</li>
 * <li>world_edit</li>
 * <li>world_go</li>
 * <li>world_link</li>
 * <li>wrench</li>
 * <li>wrench_orange</li>
 * <li>xhtml</li>
 * <li>xhtml_add</li>
 * <li>xhtml_delete</li>
 * <li>xhtml_go</li>
 * <li>xhtml_valid</li>
 * <li>zoom</li>
 * <li>zoom_in</li>
 * <li>zoom_out</li>
 * </ul>
 * 
 * @since 1.1
 * @see http://www.famfamfam.com/lab/icons/silk/
 */
@SupportsInformalParameters
public class SilkImage implements ClientElement
{
    /**
     * The name of the image. If not bound, the default is the component's id.
     */
    @Parameter(required = true, defaultPrefix = BindingConstants.LITERAL, allowNull = false)
    private String name;

    private Element element;

    private String clientId;

    @Environmental
    private JavaScriptSupport jss;

    @Inject
    private ComponentResources resources;

    @Inject
    private AssetSource assetSource;

    String defaultName()
    {
        return resources.getId();
    }

    boolean beginRender(MarkupWriter writer)
    {

        Asset asset = assetSource.getUnlocalizedAsset("com/howardlewisship/tapx/core/silk/" + name + ".png");

        // This should be handled inside AssetSource but isn't.
        // See https://issues.apache.org/jira/browse/TAP5-1425

        if (!asset.getResource().exists())
            throw new IllegalArgumentException(String.format("No Silk image named '%s.png' exists.", name));

        clientId = null;

        element = writer.element("img", "width", "16", "height", "16", "src", asset.toClientURL());
        resources.renderInformalParameters(writer);

        return false;
    }

    void afterRender(MarkupWriter writer)
    {
        writer.end();
    }

    /**
     * Returns the unique client id; this should only be invoked <em>after</em> the element renders. It will
     * allocate an id and update the rendered IMG element to include it.
     */
    public String getClientId()
    {
        if (clientId == null)
        {
            clientId = jss.allocateClientId(resources);
            element.forceAttributes("id", clientId);
        }

        return clientId;
    }
}
